---
abstract: 'Perl wrapper for the ldns DNS library.'
author:
  - 'Calle Dybedahl <calle@init.se>'
build_requires:
  Devel::CheckLib: '0.4'
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  JSON::PP: 0
  Test::Fatal: 0
configure_requires:
  Devel::CheckLib: '0.4'
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 3.18
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-LDNS
no_index:
  directory:
    - inc
    - t
requires:
  MIME::Base64: 0
  XSLoader: 0.02
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: '0.70'
